spring:
  application:
    name: payment-service
  config:
    import: configserver:http://localhost:9296
  datasource:
    username: order_user
    password: 1234
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=order
  banner:
    location: orderServiceBanner.txt

server:
  port: 8083
